[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",
    "eigenlayer-contracts/=lib/eigenlayer-contracts/src/",
    "eigenlayer-middleware/=lib/eigenlayer-middleware/src/",
    "eigenlayer-avs-playgrounds/=lib/eigenlayer-avs-playgrounds/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/"
]